# Generated by Django 5.1 on 2025-03-28 09:49

import UserApp.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_first_name', models.CharField(max_length=100)),
                ('admin_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')])),
                ('admin_password', models.CharField(max_length=128)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('franchise_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('franchise_name', models.CharField(max_length=255)),
                ('franchise_owner', models.CharField(max_length=255)),
                ('franchise_place', models.CharField(blank=True, default='Not Provided', max_length=255, null=True)),
                ('is_franchise', models.BooleanField(default=False)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('payment_status', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')])),
                ('password', models.CharField(max_length=128, null=True)),
                ('referral_code', models.CharField(default=UserApp.models.generate_referral_code, max_length=8, unique=True)),
                ('aadhar', models.CharField(blank=True, max_length=50, null=True)),
                ('GST', models.CharField(blank=True, max_length=50, null=True)),
                ('pan', models.CharField(blank=True, max_length=50, null=True)),
                ('ac_no', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid account number.', regex='^\\d{9,18}$')])),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code.', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')])),
                ('password', models.CharField(max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('adhaar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('adhaar_img', models.FileField(blank=True, null=True, upload_to='adhaar/')),
                ('pan_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_img', models.FileField(blank=True, null=True, upload_to='pancard/')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSelectionModel',
            fields=[
                ('selection_id', models.AutoField(primary_key=True, serialize=False)),
                ('selection', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.franchise')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAssignmentModel',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('franchise_mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('franchise_place', models.CharField(blank=True, max_length=255, null=True)),
                ('franchise_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='UserApp.franchise')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by', to='UserApp.staffmodel')),
                ('staff_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='UserApp.staffmodel')),
            ],
        ),
        migrations.AddField(
            model_name='franchise',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.staffmodel'),
        ),
        migrations.CreateModel(
            name='LoanApplicationModel',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('guaranter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guaranter_phoneno', models.CharField(blank=True, max_length=50, null=True)),
                ('guaranter_job', models.CharField(blank=True, max_length=100, null=True)),
                ('guaranter_cibil_score', models.CharField(blank=True, max_length=50, null=True)),
                ('guaranter_cibil_issue', models.TextField(blank=True, null=True)),
                ('guaranter_it_payable', models.BooleanField(default=False)),
                ('guaranter_years', models.IntegerField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('cibil_score', models.CharField(blank=True, max_length=100, null=True)),
                ('cibil_issue', models.TextField(blank=True, null=True)),
                ('it_payable', models.BooleanField(default=False)),
                ('years', models.IntegerField(blank=True, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('followup_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('application_description', models.TextField(blank=True, null=True)),
                ('executive_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileno_1', models.CharField(blank=True, max_length=15, null=True)),
                ('mobileno_2', models.CharField(blank=True, max_length=15, null=True)),
                ('document_description', models.TextField(blank=True, null=True)),
                ('bank_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.bankmodel')),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='UserApp.franchise')),
                ('loan_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.loanmodel')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.staffmodel')),
                ('status_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.statusmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='files/')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='UserApp.loanapplicationmodel')),
            ],
        ),
    ]
