# Generated by Django 5.1 on 2025-03-10 10:00

import UserApp.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_first_name', models.CharField(max_length=100)),
                ('admin_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')])),
                ('admin_password', models.CharField(max_length=128)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('franchise_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('franchise_name', models.CharField(max_length=255)),
                ('franchise_owner', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')])),
                ('password', models.CharField(max_length=128, null=True)),
                ('referral_code', models.CharField(default=UserApp.models.generate_referral_code, max_length=8, unique=True)),
                ('aadhar', models.FileField(upload_to='files/')),
                ('GST', models.FileField(upload_to='files/')),
                ('pan', models.FileField(upload_to='files/')),
                ('photo', models.FileField(upload_to='files/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSelectionModel',
            fields=[
                ('selection_id', models.AutoField(primary_key=True, serialize=False)),
                ('selection', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_phoneno', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_range', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FranchiseWallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='UserApp.franchise')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplicationModel',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('franchise_referral', models.CharField(blank=True, max_length=8, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('guaranter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guaranter_phoneno', models.CharField(blank=True, max_length=50, null=True)),
                ('guaranter_job', models.CharField(blank=True, max_length=100, null=True)),
                ('guaranter_cibil_score', models.CharField(blank=True, max_length=50, null=True)),
                ('guaranter_cibil_issue', models.TextField(blank=True, null=True)),
                ('guaranter_it_payable', models.BooleanField(default=False)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('cibil_score', models.CharField(blank=True, max_length=100, null=True)),
                ('cibil_issue', models.TextField(blank=True, null=True)),
                ('it_payable', models.BooleanField(default=False)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('application_description', models.TextField(blank=True, null=True)),
                ('executive_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileno_1', models.CharField(blank=True, max_length=15, null=True)),
                ('mobileno_2', models.CharField(blank=True, max_length=15, null=True)),
                ('document_description', models.TextField(blank=True, null=True)),
                ('workstatus', models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.bankmodel')),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.franchise')),
                ('loan_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.loanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')])),
                ('password', models.CharField(max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.franchise')),
                ('managed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_staff', to='UserApp.adminmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAssignmentModel',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('loan_type', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='UserApp.staffmodel')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by', to='UserApp.staffmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('adhaar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('adhaar_img', models.FileField(blank=True, null=True, upload_to='adhaar/')),
                ('pan_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_img', models.FileField(blank=True, null=True, upload_to='pancard/')),
                ('cancelled_check', models.FileField(blank=True, null=True, upload_to='cancelled_check/')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.staffmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LoanStatusUpdateHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='UserApp.loanapplicationmodel')),
                ('updated_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.adminmodel')),
                ('updated_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.staffmodel')),
            ],
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.staffmodel'),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='status_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.statusmodel'),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='files/')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='UserApp.loanapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.adminmodel')),
                ('processed_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.staffmodel')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='UserApp.franchisewallet')),
            ],
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='guaranter_years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranter_year', to='UserApp.yearmodel'),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_year', to='UserApp.yearmodel'),
        ),
    ]
