# Generated by Django 5.1 on 2025-03-17 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='franchise',
            name='ac_no',
            field=models.CharField(default=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid account number.', regex='^\\d{9,18}$')]),
        ),
        migrations.AddField(
            model_name='franchise',
            name='ifsc_code',
            field=models.CharField(default=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code.', regex='^[A-Z]{4}0[A-Z0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='GST',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='aadhar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='pan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
