# Generated by Django 5.1 on 2025-03-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='managed_by',
        ),
    ]
