# Generated by Django 5.1 on 2025-03-17 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_usermodel_franchise_ac_no_franchise_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='ac_no',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid account number.', regex='^\\d{9,18}$')]),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code.', regex='^[A-Z]{4}0[A-Z0-9]{6}$')]),
        ),
    ]
