# Generated by Django 5.1 on 2025-03-12 06:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_remove_staffmodel_franchise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileupdate',
            name='staff',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='guaranter_years',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='years',
        ),
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='loan_name',
        ),
        migrations.AddField(
            model_name='franchise',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.staffmodel'),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='status_name',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='workstatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProfileUpdate',
        ),
        migrations.DeleteModel(
            name='YearModel',
        ),
    ]
