# Generated by Django 5.1 on 2025-03-25 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_franchise_ac_no_alter_franchise_ifsc_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='franchise_referral',
        ),
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='year',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='cancelled_check',
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='loan_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.loanmodel'),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffassignmentmodel',
            name='staff_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.bankmodel'),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='followup_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.franchise'),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='guaranter_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='status_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.statusmodel'),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='workstatus',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Not selected', 'Not selected')], default='Not selected', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='LoanStatusUpdateHistory',
        ),
    ]
