# Generated by Django 5.1 on 2025-03-25 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_remove_franchise_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.staffmodel'),
        ),
    ]
