# Generated by Django 5.1 on 2025-03-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_staffmodel_account_no_staffmodel_adhaar_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='staff',
        ),
    ]
