# Generated by Django 5.1 on 2025-03-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_loanapplicationmodel_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmodel',
            name='bank_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
