# Generated by Django 5.1 on 2025-03-26 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_bankmodel_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='UserApp.franchise'),
        ),
        migrations.AlterField(
            model_name='staffassignmentmodel',
            name='franchise_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='UserApp.franchise'),
        ),
    ]
