# Generated by Django 5.1 on 2025-03-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_alter_loanapplicationmodel_franchise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='processed_by_admin',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='processed_by_staff',
        ),
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='workstatus',
        ),
        migrations.AddField(
            model_name='franchise',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='FranchiseWallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
