# Generated by Django 5.1 on 2025-03-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_remove_wallettransaction_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
