# Generated by Django 5.1 on 2025-03-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_staffmodel_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='is_franchise',
            field=models.BooleanField(default=False),
        ),
    ]
