# Generated by Django 5.1 on 2025-03-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_franchise_is_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
